// -- BuddyCode — Problem Database ------------------------------------
// Format: { slug: { time, space, elo, freq (0-100 normalized), companies: [...] } }
// freq ˜ how many companies ask this problem, normalized to a 0-100 scale
// elo ˜ contest rating (harder problems have higher ratings)
const PROBLEM_DB = {

  // -- Array / Hash Table -------------------------------------------------
  "two-sum":                    { time:"O(n)",  space:"O(n)",   elo:null, freq:100, companies:["Google","Amazon","Adobe","Apple","Microsoft","Bloomberg","Meta","Uber","Oracle","Yahoo"] },
  "best-time-to-buy-and-sell-stock": { time:"O(n)", space:"O(1)", elo:null, freq:69.8, companies:["Amazon","Meta","Microsoft","Bloomberg","Apple","Google"] },
  "contains-duplicate":         { time:"O(n)",  space:"O(n)",   elo:null, freq:16.3, companies:["Amazon","Apple","Google","Microsoft","Adobe"] },
  "product-of-array-except-self": { time:"O(n)", space:"O(1)",  elo:null, freq:34.1, companies:["Amazon","Meta","Microsoft","Apple","Bloomberg","Google","Uber","LinkedIn"] },
  "maximum-subarray":           { time:"O(n)",  space:"O(1)",   elo:null, freq:51.2, companies:["Amazon","Microsoft","Google","LinkedIn","Apple","Meta","Bloomberg","Adobe"] },
  "maximum-product-subarray":   { time:"O(n)",  space:"O(1)",   elo:null, freq:19.4, companies:["Amazon","Google","LinkedIn","Microsoft","Apple"] },
  "find-minimum-in-rotated-sorted-array": { time:"O(log n)", space:"O(1)", elo:null, freq:13.2, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },
  "search-in-rotated-sorted-array": { time:"O(log n)", space:"O(1)", elo:null, freq:38.8, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","LinkedIn"] },
  "3sum":                       { time:"O(n²)", space:"O(1)",   elo:null, freq:44.2, companies:["Amazon","Meta","Microsoft","Google","Apple","Bloomberg","Adobe"] },
  "container-with-most-water":  { time:"O(n)",  space:"O(1)",   elo:null, freq:43.4, companies:["Amazon","Google","Microsoft","Apple","Adobe"] },
  "subarray-sum-equals-k":      { time:"O(n)",  space:"O(n)",   elo:null, freq:35.7, companies:["Amazon","Meta","Google","Microsoft","Bloomberg","Apple"] },
  "merge-intervals":            { time:"O(n log n)", space:"O(n)", elo:null, freq:84.5, companies:["Amazon","Meta","Google","Microsoft","Apple","Bloomberg","Uber","Salesforce"] },
  "insert-interval":            { time:"O(n)",  space:"O(n)",   elo:null, freq:12.4, companies:["Google","Amazon","Meta","Microsoft","LinkedIn"] },
  "meeting-rooms":              { time:"O(n log n)", space:"O(1)", elo:null, freq:7.8, companies:["Amazon","Google","Meta","Microsoft"] },
  "meeting-rooms-ii":           { time:"O(n log n)", space:"O(n)", elo:null, freq:31.8, companies:["Amazon","Meta","Google","Microsoft","Bloomberg","Apple","Uber"] },
  "non-overlapping-intervals":  { time:"O(n log n)", space:"O(1)", elo:null, freq:14, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "group-anagrams":             { time:"O(n·k log k)", space:"O(n·k)", elo:null, freq:68.2, companies:["Amazon","Google","Microsoft","Apple","Meta","Bloomberg","Uber","Oracle"] },
  "valid-anagram":              { time:"O(n)",  space:"O(1)",   elo:null, freq:29.5, companies:["Amazon","Google","Meta","Microsoft","Bloomberg","Apple"] },
  "top-k-frequent-elements":    { time:"O(n log k)", space:"O(n)", elo:null, freq:40.3, companies:["Amazon","Meta","Google","Microsoft","Bloomberg","Apple","LinkedIn"] },
  "find-all-anagrams-in-a-string": { time:"O(n)", space:"O(1)", elo:null, freq:12.4, companies:["Amazon","Microsoft","Google","Meta","Bloomberg","Apple"] },
  "longest-consecutive-sequence": { time:"O(n)", space:"O(n)",  elo:null, freq:31, companies:["Amazon","Google","Microsoft","Meta","Bloomberg","Apple","Uber"] },

  // -- Two Pointers / Sliding Window --------------------------------------
  "valid-palindrome":           { time:"O(n)",  space:"O(1)",   elo:null, freq:34.1, companies:["Meta","Amazon","Microsoft","Google","Apple","Bloomberg"] },
  "longest-substring-without-repeating-characters": { time:"O(n)", space:"O(1)", elo:null, freq:80.6, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber","Adobe"] },
  "longest-repeating-character-replacement": { time:"O(n)", space:"O(1)", elo:null, freq:17.1, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "minimum-window-substring":   { time:"O(n)",  space:"O(1)",   elo:null, freq:27.9, companies:["Amazon","Meta","Microsoft","Google","Apple","Bloomberg","Uber","LinkedIn","Lyft"] },
  "permutation-in-string":      { time:"O(n)",  space:"O(1)",   elo:null, freq:12.4, companies:["Amazon","Microsoft","Google","Meta","Bloomberg"] },
  "trapping-rain-water":        { time:"O(n)",  space:"O(1)",   elo:null, freq:58.1, companies:["Amazon","Google","Microsoft","Meta","Apple","Bloomberg","Uber","Goldman Sachs"] },
  "sliding-window-maximum":     { time:"O(n)",  space:"O(k)",   elo:null, freq:35.7, companies:["Amazon","Google","Microsoft","Meta","Bloomberg","Uber","Apple"] },
  "remove-duplicates-from-sorted-array": { time:"O(n)", space:"O(1)", elo:null, freq:20.9, companies:["Amazon","Google","Microsoft","Meta","Bloomberg"] },
  "move-zeroes":                { time:"O(n)",  space:"O(1)",   elo:null, freq:36.4, companies:["Amazon","Meta","Microsoft","Google","Apple","Bloomberg"] },
  "squares-of-a-sorted-array":  { time:"O(n)",  space:"O(n)",   elo:null, freq:13.2, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "sort-colors":                { time:"O(n)",  space:"O(1)",   elo:null, freq:28.7, companies:["Amazon","Microsoft","Google","Meta","Bloomberg","Apple"] },
  "palindromic-substrings":     { time:"O(n²)", space:"O(1)",   elo:null, freq:19.4, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "longest-palindromic-substring": { time:"O(n²)", space:"O(1)", elo:null, freq:62, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Adobe"] },

  // -- Linked Lists -------------------------------------------------------
  "reverse-linked-list":        { time:"O(n)",  space:"O(1)",   elo:null, freq:26.4, companies:["Amazon","Microsoft","Google","Meta","Apple","Bloomberg","Adobe"] },
  "merge-two-sorted-lists":    { time:"O(n+m)", space:"O(1)",   elo:null, freq:29.5, companies:["Amazon","Microsoft","Google","Meta","Apple","Bloomberg","Adobe"] },
  "linked-list-cycle":          { time:"O(n)",  space:"O(1)",   elo:null, freq:19.4, companies:["Amazon","Microsoft","Google","Meta","Apple","Bloomberg","Salesforce"] },
  "reorder-list":               { time:"O(n)",  space:"O(1)",   elo:null, freq:12.4, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },
  "remove-nth-node-from-end-of-list": { time:"O(n)", space:"O(1)", elo:null, freq:14, companies:["Amazon","Microsoft","Google","Meta","Bloomberg","Apple"] },
  "add-two-numbers":            { time:"O(max(n,m))", space:"O(max(n,m))", elo:null, freq:27.1, companies:["Amazon","Microsoft","Google","Meta","Bloomberg","Apple","Uber","Adobe"] },
  "merge-k-sorted-lists":       { time:"O(n log k)", space:"O(k)", elo:null, freq:38.8, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber","Oracle"] },
  "intersection-of-two-linked-lists": { time:"O(n+m)", space:"O(1)", elo:null, freq:10.1, companies:["Amazon","Microsoft","Google","Meta","Apple","LinkedIn"] },
  "palindrome-linked-list":     { time:"O(n)",  space:"O(1)",   elo:null, freq:12.4, companies:["Amazon","Microsoft","Google","Meta","Apple","Bloomberg"] },
  "lru-cache":                  { time:"O(1)",  space:"O(capacity)", elo:null, freq:96.9, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber","Salesforce","Oracle","Goldman Sachs"] },

  // -- Trees / BST --------------------------------------------------------
  "maximum-depth-of-binary-tree": { time:"O(n)", space:"O(h)", elo:null, freq:12.4, companies:["Amazon","Microsoft","Google","Meta","Apple","Bloomberg","LinkedIn"] },
  "same-tree":                  { time:"O(n)",  space:"O(h)",   elo:null, freq:7, companies:["Amazon","Google","Microsoft","Meta","Bloomberg"] },
  "invert-binary-tree":         { time:"O(n)",  space:"O(h)",   elo:null, freq:7.8, companies:["Amazon","Google","Microsoft","Meta","Bloomberg"] },
  "binary-tree-level-order-traversal": { time:"O(n)", space:"O(n)", elo:null, freq:10.9, companies:["Amazon","Microsoft","Google","Meta","Bloomberg","Apple"] },
  "subtree-of-another-tree":    { time:"O(m·n)", space:"O(h)",  elo:null, freq:6.2, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },
  "lowest-common-ancestor-of-a-binary-search-tree": { time:"O(h)", space:"O(1)", elo:null, freq:7.8, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","LinkedIn"] },
  "lowest-common-ancestor-of-a-binary-tree": { time:"O(n)", space:"O(h)", elo:null, freq:17.1, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","LinkedIn"] },
  "construct-binary-tree-from-preorder-and-inorder-traversal": { time:"O(n)", space:"O(n)", elo:null, freq:7, companies:["Amazon","Microsoft","Google","Meta","Bloomberg","Apple"] },
  "validate-binary-search-tree": { time:"O(n)", space:"O(h)",  elo:null, freq:13.2, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber","LinkedIn"] },
  "kth-smallest-element-in-a-bst": { time:"O(n)", space:"O(h)", elo:null, freq:8.5, companies:["Amazon","Google","Microsoft","Meta","Bloomberg","Apple"] },
  "binary-tree-maximum-path-sum": { time:"O(n)", space:"O(h)", elo:null, freq:17.8, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber"] },
  "serialize-and-deserialize-binary-tree": { time:"O(n)", space:"O(n)", elo:null, freq:18.6, companies:["Amazon","Microsoft","Google","Meta","Apple","Bloomberg","Uber","LinkedIn","Oracle"] },
  "binary-tree-right-side-view": { time:"O(n)", space:"O(n)",  elo:null, freq:11.6, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },
  "count-good-nodes-in-binary-tree": { time:"O(n)", space:"O(h)", elo:null, freq:5.4, companies:["Amazon","Microsoft","Google","Meta","Bloomberg"] },
  "diameter-of-binary-tree":    { time:"O(n)",  space:"O(h)",   elo:null, freq:14.7, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },
  "balanced-binary-tree":       { time:"O(n)",  space:"O(h)",   elo:null, freq:5.4, companies:["Amazon","Microsoft","Google","Meta","Bloomberg"] },

  // -- Graphs / BFS / DFS -------------------------------------------------
  "number-of-islands":          { time:"O(m·n)", space:"O(m·n)", elo:null, freq:62.8, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber","LinkedIn","Oracle"] },
  "clone-graph":                { time:"O(n+e)", space:"O(n)",  elo:null, freq:14, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber"] },
  "course-schedule":            { time:"O(n+p)", space:"O(n+p)", elo:null, freq:31.8, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber","Lyft"] },
  "course-schedule-ii":         { time:"O(n+p)", space:"O(n+p)", elo:null, freq:27.1, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber","Intuit"] },
  "pacific-atlantic-water-flow": { time:"O(m·n)", space:"O(m·n)", elo:null, freq:9.3, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },
  "rotting-oranges":            { time:"O(m·n)", space:"O(m·n)", elo:null, freq:38.8, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber"] },
  "word-ladder":                { time:"O(n·m²)", space:"O(n)", elo:null, freq:31, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber","LinkedIn","Lyft"] },
  "word-ladder-ii":             { time:"O(n·m·L)", space:"O(n·m·L)", elo:null, freq:15.5, companies:["Amazon","Meta","Google","Microsoft","Bloomberg","Apple"] },
  "walls-and-gates":            { time:"O(m·n)", space:"O(m·n)", elo:null, freq:9.3, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "graph-valid-tree":           { time:"O(n+e)", space:"O(n+e)", elo:null, freq:7, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "number-of-connected-components-in-an-undirected-graph": { time:"O(n+e)", space:"O(n+e)", elo:null, freq:5.4, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "alien-dictionary":           { time:"O(c+a)", space:"O(1)",  elo:null, freq:12.4, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber","Airbnb","Pinterest"] },
  "redundant-connection":       { time:"O(n·a(n))", space:"O(n)", elo:null, freq:6.2, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "cheapest-flights-within-k-stops": { time:"O(n·k)", space:"O(n)", elo:null, freq:14, companies:["Amazon","Meta","Google","Microsoft","Uber","Bloomberg","Airbnb"] },
  "word-search":                { time:"O(m·n·4^L)", space:"O(L)", elo:null, freq:27.9, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber","Snap"] },
  "word-search-ii":             { time:"O(m·n·4^L)", space:"O(w·l)", elo:null, freq:15.5, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber","Airbnb"] },
  "surrounded-regions":         { time:"O(m·n)", space:"O(m·n)", elo:null, freq:9.3, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "max-area-of-island":         { time:"O(m·n)", space:"O(m·n)", elo:null, freq:14.7, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },

  // -- Dynamic Programming ------------------------------------------------
  "climbing-stairs":            { time:"O(n)",  space:"O(1)",   elo:null, freq:28.7, companies:["Amazon","Microsoft","Google","Meta","Apple","Bloomberg","Adobe","Uber"] },
  "coin-change":                { time:"O(n·m)", space:"O(n)",  elo:null, freq:32.6, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber","Airbnb"] },
  "longest-increasing-subsequence": { time:"O(n log n)", space:"O(n)", elo:null, freq:24, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber"] },
  "longest-common-subsequence": { time:"O(m·n)", space:"O(m·n)", elo:null, freq:15.5, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber","Goldman Sachs"] },
  "word-break":                 { time:"O(n²)", space:"O(n)",   elo:null, freq:24.8, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber","Oracle"] },
  "combination-sum-iv":         { time:"O(n·t)", space:"O(t)",  elo:null, freq:4.7, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "house-robber":               { time:"O(n)",  space:"O(1)",   elo:null, freq:29.5, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },
  "house-robber-ii":            { time:"O(n)",  space:"O(1)",   elo:null, freq:14.7, companies:["Amazon","Microsoft","Google","Meta","Bloomberg","Apple"] },
  "decode-ways":                { time:"O(n)",  space:"O(1)",   elo:null, freq:17.1, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber","Lyft"] },
  "unique-paths":               { time:"O(m·n)", space:"O(n)",  elo:null, freq:15.5, companies:["Amazon","Google","Microsoft","Meta","Bloomberg","Apple"] },
  "jump-game":                  { time:"O(n)",  space:"O(1)",   elo:null, freq:25.6, companies:["Amazon","Microsoft","Google","Meta","Apple","Bloomberg"] },
  "jump-game-ii":               { time:"O(n)",  space:"O(1)",   elo:null, freq:19.4, companies:["Amazon","Microsoft","Google","Meta","Bloomberg"] },
  "partition-equal-subset-sum": { time:"O(n·s)", space:"O(s)",  elo:null, freq:12.4, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },
  "target-sum":                 { time:"O(n·s)", space:"O(s)",  elo:null, freq:8.5, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "edit-distance":              { time:"O(m·n)", space:"O(m·n)", elo:null, freq:20.9, companies:["Amazon","Meta","Google","Microsoft","Bloomberg","Apple","Uber"] },
  "burst-balloons":             { time:"O(n³)", space:"O(n²)",  elo:null, freq:10.9, companies:["Amazon","Meta","Google","Microsoft","Bloomberg","Apple","Uber"] },
  "regular-expression-matching": { time:"O(m·n)", space:"O(m·n)", elo:null, freq:19.4, companies:["Amazon","Meta","Google","Microsoft","Bloomberg","Apple","Uber","Airbnb"] },
  "palindrome-partitioning":    { time:"O(n·2^n)", space:"O(n)", elo:null, freq:7, companies:["Amazon","Meta","Google","Microsoft","Bloomberg","Apple"] },
  "interleaving-string":        { time:"O(m·n)", space:"O(m·n)", elo:null, freq:8.5, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "min-cost-climbing-stairs":   { time:"O(n)",  space:"O(1)",   elo:null, freq:5.4, companies:["Amazon","Google","Microsoft","Meta","Bloomberg"] },
  "paint-house":                { time:"O(n)",  space:"O(1)",   elo:null, freq:6.2, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","LinkedIn"] },

  // -- Intervals ----------------------------------------------------------
  "minimum-number-of-arrows-to-burst-balloons": { time:"O(n log n)", space:"O(1)", elo:null, freq:6.2, companies:["Amazon","Microsoft","Google","Meta","Bloomberg"] },
  "employee-free-time":         { time:"O(n log n)", space:"O(n)", elo:null, freq:9.3, companies:["Amazon","Meta","Google","Microsoft","Bloomberg","Uber","Pinterest"] },
  "interval-list-intersections": { time:"O(n+m)", space:"O(n+m)", elo:null, freq:9.3, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "data-stream-as-disjoint-intervals": { time:"O(log n)", space:"O(n)", elo:null, freq:1.6, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "minimum-interval-to-include-each-query": { time:"O((n+q) log n)", space:"O(n)", elo:null, freq:2.3, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },

  // -- Heap / Priority Queue ----------------------------------------------
  "kth-largest-element-in-an-array": { time:"O(n log k)", space:"O(k)", elo:null, freq:32.6, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber","LinkedIn"] },
  "find-median-from-data-stream": { time:"O(log n)", space:"O(n)", elo:null, freq:29.5, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber","Goldman Sachs"] },
  "k-closest-points-to-origin": { time:"O(n log k)", space:"O(k)", elo:null, freq:13.2, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber"] },
  "task-scheduler":             { time:"O(n log n)", space:"O(1)", elo:null, freq:19.4, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber"] },
  "design-twitter":             { time:"O(log n)", space:"O(n)",  elo:null, freq:10.9, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "reorganize-string":          { time:"O(n log n)", space:"O(n)", elo:null, freq:16.3, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber"] },
  "kth-largest-element-in-a-stream": { time:"O(log k)", space:"O(k)", elo:null, freq:8.5, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "last-stone-weight":          { time:"O(n log n)", space:"O(n)", elo:null, freq:10.1, companies:["Amazon","Google","Microsoft","Meta","Bloomberg"] },
  "jump-game-vi":               { time:"O(n)",  space:"O(n)",   elo:null, freq:4.7, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "single-threaded-cpu":        { time:"O(n log n)", space:"O(n)", elo:null, freq:5.4, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },

  // -- Binary Search ------------------------------------------------------
  "binary-search":              { time:"O(log n)", space:"O(1)", elo:null, freq:9.3, companies:["Amazon","Google","Microsoft","Meta","Bloomberg","Apple"] },
  "search-a-2d-matrix":         { time:"O(log(m·n))", space:"O(1)", elo:null, freq:14, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },
  "median-of-two-sorted-arrays": { time:"O(log(m+n))", space:"O(1)", elo:null, freq:34.9, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber","Goldman Sachs","Adobe"] },
  "koko-eating-bananas":        { time:"O(n log m)", space:"O(1)", elo:null, freq:29.5, companies:["Amazon","Meta","Google","Microsoft","Bloomberg","Apple"] },
  "time-based-key-value-store": { time:"O(log n)", space:"O(n)", elo:null, freq:26.4, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Lyft"] },
  "find-first-and-last-position-of-element-in-sorted-array": { time:"O(log n)", space:"O(1)", elo:null, freq:22.5, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","LinkedIn"] },
  "capacity-to-ship-packages-within-d-days": { time:"O(n log s)", space:"O(1)", elo:null, freq:16.3, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "find-peak-element":          { time:"O(log n)", space:"O(1)", elo:null, freq:25.6, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },
  "search-in-rotated-sorted-array-ii": { time:"O(n)", space:"O(1)", elo:null, freq:8.5, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "split-array-largest-sum":    { time:"O(n log s)", space:"O(1)", elo:null, freq:14.7, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "minimum-number-of-days-to-make-m-bouquets": { time:"O(n log m)", space:"O(1)", elo:null, freq:7, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "aggressive-cows":            { time:"O(n log m)", space:"O(1)", elo:null, freq:3.1, companies:["Amazon","Meta","Google","Microsoft"] },

  // -- Backtracking -------------------------------------------------------
  "subsets":                    { time:"O(n·2^n)", space:"O(n)", elo:null, freq:15.5, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },
  "subsets-ii":                 { time:"O(n·2^n)", space:"O(n)", elo:null, freq:7, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },
  "combination-sum":            { time:"O(n·2^t)", space:"O(t)", elo:null, freq:20.9, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber","Airbnb"] },
  "combination-sum-ii":         { time:"O(n·2^n)", space:"O(n)", elo:null, freq:11.6, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },
  "permutations":               { time:"O(n·n!)", space:"O(n)",  elo:null, freq:19.4, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","LinkedIn"] },
  "permutations-ii":            { time:"O(n·n!)", space:"O(n)",  elo:null, freq:7, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "letter-combinations-of-a-phone-number": { time:"O(n·4^n)", space:"O(n)", elo:null, freq:26.4, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber"] },
  "generate-parentheses":       { time:"O(4^n/vn)", space:"O(n)", elo:null, freq:31, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber","Adobe"] },
  "n-queens":                   { time:"O(n!)", space:"O(n)",    elo:null, freq:11.6, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },
  "restore-ip-addresses":       { time:"O(1)", space:"O(1)",     elo:null, freq:14.7, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "sudoku-solver":              { time:"O(9^(n²))", space:"O(n²)", elo:null, freq:13.2, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber","Airbnb"] },
  "word-break-ii":              { time:"O(n·2^n)", space:"O(n·2^n)", elo:null, freq:12.4, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber","Snap"] },

  // -- Greedy -------------------------------------------------------------
  "gas-station":                { time:"O(n)",  space:"O(1)",   elo:null, freq:20.9, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },
  "hand-of-straights":          { time:"O(n log n)", space:"O(n)", elo:null, freq:4.7, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "partition-labels":           { time:"O(n)",  space:"O(1)",   elo:null, freq:7, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "merge-triplets-to-form-target-triplet": { time:"O(n)", space:"O(1)", elo:null, freq:0.8, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "maximum-subarray-sum-circular": { time:"O(n)", space:"O(1)", elo:null, freq:3.9, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "minimum-rounds-to-complete-all-tasks": { time:"O(n)", space:"O(n)", elo:null, freq:1.6, companies:["Amazon","Meta","Google","Microsoft"] },
  "dota2-senate":               { time:"O(n)",  space:"O(n)",   elo:null, freq:4.7, companies:["Amazon","Meta","Google","Microsoft"] },
  "rearrange-array-elements-by-sign": { time:"O(n)", space:"O(n)", elo:null, freq:4.7, companies:["Amazon","Meta","Google","Microsoft"] },

  // -- Math / Bit Manipulation --------------------------------------------
  "single-number":              { time:"O(n)",  space:"O(1)",   elo:null, freq:11.6, companies:["Amazon","Google","Microsoft","Meta","Bloomberg","Apple","Adobe"] },
  "number-of-1-bits":           { time:"O(k)",  space:"O(1)",   elo:null, freq:8.5, companies:["Amazon","Google","Microsoft","Meta","Bloomberg","Apple"] },
  "counting-bits":              { time:"O(n)",  space:"O(n)",   elo:null, freq:7.8, companies:["Amazon","Google","Microsoft","Meta","Bloomberg","Apple"] },
  "missing-number":             { time:"O(n)",  space:"O(1)",   elo:null, freq:14.7, companies:["Amazon","Microsoft","Google","Meta","Bloomberg","Apple"] },
  "reverse-integer":            { time:"O(log n)", space:"O(1)", elo:null, freq:17.8, companies:["Amazon","Google","Microsoft","Meta","Bloomberg","Apple"] },
  "powx-n":                     { time:"O(log n)", space:"O(log n)", elo:null, freq:17.1, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","LinkedIn"] },
  "multiply-strings":           { time:"O(m·n)", space:"O(m+n)", elo:null, freq:13.2, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber"] },
  "set-matrix-zeroes":          { time:"O(m·n)", space:"O(1)",  elo:null, freq:17.8, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber"] },
  "spiral-matrix":              { time:"O(m·n)", space:"O(1)",  elo:null, freq:41.1, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber"] },
  "rotate-image":               { time:"O(n²)", space:"O(1)",   elo:null, freq:28.7, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Adobe"] },
  "plus-one":                   { time:"O(n)",  space:"O(1)",   elo:null, freq:10.1, companies:["Amazon","Google","Microsoft","Meta","Bloomberg","Apple"] },
  "sum-of-two-integers":        { time:"O(1)",  space:"O(1)",   elo:null, freq:6.2, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "happy-number":               { time:"O(log n)", space:"O(1)", elo:null, freq:20.9, companies:["Amazon","Google","Microsoft","Meta","Bloomberg","Apple","Uber"] },

  // -- String -------------------------------------------------------------
  "valid-parentheses":          { time:"O(n)",  space:"O(n)",   elo:null, freq:89.9, companies:["Amazon","Microsoft","Google","Meta","Apple","Bloomberg","Uber","LinkedIn","Adobe","Oracle"] },
  "encode-and-decode-strings":  { time:"O(n)",  space:"O(1)",   elo:null, freq:8.5, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber"] },
  "valid-parenthesis-string":   { time:"O(n)",  space:"O(1)",   elo:null, freq:11.6, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },
  "minimum-remove-to-make-valid-parentheses": { time:"O(n)", space:"O(n)", elo:null, freq:8.5, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber"] },
  "implement-strstr":           { time:"O(n·m)", space:"O(1)",  elo:null, freq:4.7, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },

  // -- Stack / Monotonic Stack --------------------------------------------
  "daily-temperatures":         { time:"O(n)",  space:"O(n)",   elo:null, freq:24, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },
  "largest-rectangle-in-histogram": { time:"O(n)", space:"O(n)", elo:null, freq:23.3, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber"] },
  "min-stack":                  { time:"O(1)",  space:"O(n)",   elo:null, freq:30.2, companies:["Amazon","Microsoft","Google","Meta","Bloomberg","Apple","Uber","Salesforce","Oracle"] },
  "evaluate-reverse-polish-notation": { time:"O(n)", space:"O(n)", elo:null, freq:14, companies:["Amazon","Meta","Google","Microsoft","Bloomberg","Apple","LinkedIn"] },
  "car-fleet":                  { time:"O(n log n)", space:"O(n)", elo:null, freq:9.3, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "asteroid-collision":         { time:"O(n)",  space:"O(n)",   elo:null, freq:26.4, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Lyft"] },
  "remove-k-digits":            { time:"O(n)",  space:"O(n)",   elo:null, freq:17.8, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },
  "basic-calculator-ii":        { time:"O(n)",  space:"O(n)",   elo:null, freq:25.6, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber","LinkedIn"] },
  "decode-string":              { time:"O(n)",  space:"O(n)",   elo:null, freq:31, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber"] },
  "simplify-path":              { time:"O(n)",  space:"O(n)",   elo:null, freq:18.6, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },
  "maximal-rectangle":          { time:"O(m·n)", space:"O(n)",  elo:null, freq:11.6, companies:["Amazon","Meta","Google","Microsoft","Bloomberg","Apple","Uber"] },

  // -- Trie ---------------------------------------------------------------
  "implement-trie-prefix-tree": { time:"O(L)",  space:"O(n·L)", elo:null, freq:17.1, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber","Twitter"] },
  "design-add-and-search-words-data-structure": { time:"O(L·26)", space:"O(n·L)", elo:null, freq:11.6, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber","Twitter"] },
  "maximum-xor-of-two-numbers-in-an-array": { time:"O(n)", space:"O(n)", elo:null, freq:4.7, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "concatenated-words":         { time:"O(n·L²)", space:"O(n·L)", elo:null, freq:2.3, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "prefix-and-suffix-search":   { time:"O(L²)", space:"O(n·L²)", elo:null, freq:2.3, companies:["Amazon","Meta","Google","Microsoft"] },
  "palindrome-pairs":           { time:"O(n·L²)", space:"O(n·L)", elo:null, freq:5.4, companies:["Amazon","Meta","Google","Microsoft","Bloomberg","Airbnb"] },
  "replace-words":              { time:"O(n·L)", space:"O(n·L)", elo:null, freq:3.9, companies:["Amazon","Meta","Google","Microsoft"] },
  "implement-magic-dictionary": { time:"O(L·26)", space:"O(n·L)", elo:null, freq:1.6, companies:["Amazon","Meta","Google","Microsoft"] },
  "top-k-frequent-words":       { time:"O(n log k)", space:"O(n)", elo:null, freq:18.6, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber","Oracle"] },

  // -- Union Find ---------------------------------------------------------
  "accounts-merge":             { time:"O(n·k·a(n))", space:"O(n·k)", elo:null, freq:14, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber"] },
  "number-of-islands-ii":       { time:"O(k·a(mn))", space:"O(m·n)", elo:null, freq:7.8, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "satisfiability-of-equality-equations": { time:"O(n·a(1))", space:"O(1)", elo:null, freq:4.7, companies:["Amazon","Meta","Google","Microsoft"] },
  "regions-cut-by-slashes":     { time:"O(n²·a(n²))", space:"O(n²)", elo:null, freq:5.4, companies:["Amazon","Meta","Google","Microsoft"] },
  "most-stones-removed-with-same-row-or-column": { time:"O(n·a(n))", space:"O(n)", elo:null, freq:7.8, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "minimize-malware-spread":    { time:"O(n²·a(n))", space:"O(n)", elo:null, freq:7.8, companies:["Amazon","Meta","Google","Microsoft"] },
  "minimize-malware-spread-ii": { time:"O(n²·a(n))", space:"O(n)", elo:null, freq:1.6, companies:["Amazon","Meta","Google","Microsoft"] },
  "couples-holding-hands":      { time:"O(n·a(n))", space:"O(n)", elo:null, freq:3.9, companies:["Amazon","Meta","Google","Microsoft"] },

  // -- Matrix -------------------------------------------------------------
  "valid-sudoku":               { time:"O(1)",  space:"O(1)",   elo:null, freq:18.6, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber"] },
  "search-a-2d-matrix-ii":      { time:"O(m+n)", space:"O(1)",  elo:null, freq:13.2, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },
  "game-of-life":               { time:"O(m·n)", space:"O(1)",  elo:null, freq:12.4, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber","Dropbox"] },
  "shortest-path-in-binary-matrix": { time:"O(n²)", space:"O(n²)", elo:null, freq:12.4, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },

  // -- More Popular Problems ----------------------------------------------
  "flood-fill":                 { time:"O(m·n)", space:"O(m·n)", elo:null, freq:9.3, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "01-matrix":                  { time:"O(m·n)", space:"O(m·n)", elo:null, freq:11.6, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "course-schedule-iii":       { time:"O(n log n)", space:"O(n)", elo:null, freq:3.1, companies:["Amazon","Meta","Google","Microsoft"] },
  "swim-in-rising-water":      { time:"O(n² log n)", space:"O(n²)", elo:null, freq:6.2, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "path-with-minimum-effort":  { time:"O(m·n log(mn))", space:"O(m·n)", elo:null, freq:7, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "network-delay-time":        { time:"O(n + e log n)", space:"O(n+e)", elo:null, freq:6.2, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },
  "reconstruct-itinerary":     { time:"O(e log e)", space:"O(e)", elo:null, freq:17.1, companies:["Amazon","Meta","Google","Microsoft","Bloomberg","Apple","Uber"] },
  "longest-increasing-path-in-a-matrix": { time:"O(m·n)", space:"O(m·n)", elo:null, freq:12.4, companies:["Amazon","Meta","Google","Microsoft","Bloomberg","Apple","Uber"] },
  "race-car":                  { time:"O(t log t)", space:"O(t)", elo:null, freq:3.9, companies:["Amazon","Meta","Google","Microsoft"] },
  "minimum-knight-moves":      { time:"O(max(|x|,|y|)²)", space:"O(max(|x|,|y|)²)", elo:null, freq:10.1, companies:["Amazon","Meta","Google","Microsoft"] },
  "open-the-lock":             { time:"O(10000)", space:"O(10000)", elo:null, freq:11.6, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "best-time-to-buy-and-sell-stock-with-cooldown": { time:"O(n)", space:"O(1)", elo:null, freq:6.2, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "best-time-to-buy-and-sell-stock-ii": { time:"O(n)", space:"O(1)", elo:null, freq:21.7, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },
  "best-time-to-buy-and-sell-stock-iii": { time:"O(n)", space:"O(1)", elo:null, freq:10.9, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber"] },
  "best-time-to-buy-and-sell-stock-iv": { time:"O(n·k)", space:"O(k)", elo:null, freq:8.5, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },
  "best-time-to-buy-and-sell-stock-with-transaction-fee": { time:"O(n)", space:"O(1)", elo:null, freq:6.2, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "distinct-subsequences":     { time:"O(m·n)", space:"O(n)",  elo:null, freq:10.9, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "longest-string-chain":      { time:"O(n·L²)", space:"O(n)", elo:null, freq:12.4, companies:["Amazon","Meta","Google","Microsoft","Bloomberg","Apple"] },
  "largest-divisible-subset":  { time:"O(n²)", space:"O(n)",   elo:null, freq:4.7, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "triangle":                  { time:"O(n²)", space:"O(n)",   elo:null, freq:8.5, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "dungeon-game":              { time:"O(m·n)", space:"O(m·n)", elo:null, freq:6.2, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },
  "perfect-squares":           { time:"O(n·vn)", space:"O(n)", elo:null, freq:8.5, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },
  "russian-doll-envelopes":    { time:"O(n log n)", space:"O(n)", elo:null, freq:8.5, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "minimum-path-sum":          { time:"O(m·n)", space:"O(n)",  elo:null, freq:12.4, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber"] },
  "maximal-square":            { time:"O(m·n)", space:"O(n)",  elo:null, freq:21.7, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber"] },
  "count-square-submatrices-with-all-ones": { time:"O(m·n)", space:"O(n)", elo:null, freq:3.9, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "delete-and-earn":           { time:"O(n + m)", space:"O(m)", elo:null, freq:8.5, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "longest-arithmetic-subsequence": { time:"O(n²)", space:"O(n²)", elo:null, freq:4.7, companies:["Amazon","Meta","Google","Microsoft"] },
  "longest-arithmetic-subsequence-of-given-difference": { time:"O(n)", space:"O(n)", elo:null, freq:1.6, companies:["Amazon","Meta","Google","Microsoft"] },
  "number-of-longest-increasing-subsequence": { time:"O(n²)", space:"O(n)", elo:null, freq:5.4, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "partition-array-for-maximum-sum": { time:"O(n·k)", space:"O(n)", elo:null, freq:3.9, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "frog-jump":                 { time:"O(n²)", space:"O(n²)",  elo:null, freq:7.8, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },
  "minimum-cost-for-tickets":  { time:"O(n)",  space:"O(n)",   elo:null, freq:10.1, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "stone-game":                { time:"O(n²)", space:"O(n²)",  elo:null, freq:3.1, companies:["Amazon","Meta","Google","Microsoft"] },
  "cherry-pickup":             { time:"O(n³)", space:"O(n²)",  elo:null, freq:7, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "minimum-cost-to-merge-stones": { time:"O(n³)", space:"O(n²)", elo:null, freq:3.1, companies:["Amazon","Meta","Google","Microsoft"] },
  "super-egg-drop":            { time:"O(k log n)", space:"O(k)", elo:null, freq:3.9, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },

  // -- Design -------------------------------------------------------------
  "lfu-cache":                  { time:"O(1)",  space:"O(capacity)", elo:null, freq:24.8, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber","Salesforce"] },
  "design-hashmap":             { time:"O(1)",  space:"O(n)",   elo:null, freq:10.9, companies:["Amazon","Microsoft","Google","Meta","Bloomberg","Apple","Uber","Salesforce","LinkedIn"] },
  "design-hashset":            { time:"O(1)",  space:"O(n)",   elo:null, freq:4.7, companies:["Amazon","Microsoft","Google","Meta","Bloomberg","Apple","Uber","Salesforce"] },
  "design-circular-queue":     { time:"O(1)",  space:"O(k)",   elo:null, freq:16.3, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "design-underground-system": { time:"O(1)",  space:"O(p+s²)", elo:null, freq:5.4, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "design-browser-history":    { time:"O(1)",  space:"O(n)",   elo:null, freq:10.1, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "design-a-food-rating-system": { time:"O(log n)", space:"O(n)", elo:null, freq:3.1, companies:["Amazon","Meta","Google","Microsoft"] },
  "stock-price-fluctuation":   { time:"O(log n)", space:"O(n)", elo:null, freq:3.9, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "range-module":              { time:"O(log n)", space:"O(n)", elo:null, freq:3.9, companies:["Amazon","Meta","Google","Microsoft"] },
  "design-in-memory-file-system": { time:"O(m+n)", space:"O(n)", elo:null, freq:13.2, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "design-a-text-editor":      { time:"O(n)",  space:"O(n)",   elo:null, freq:8.5, companies:["Amazon","Meta","Google","Microsoft"] },
  "insert-delete-getrandom-o1": { time:"O(1)",  space:"O(n)",  elo:null, freq:30.2, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber","LinkedIn","Twitter","Lyft"] },
  "design-circular-deque":      { time:"O(1)",  space:"O(k)",   elo:null, freq:3.9, companies:["Amazon","Meta","Microsoft","Google"] },
  "all-oone-data-structure":   { time:"O(1)",  space:"O(n)",   elo:null, freq:8.5, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","LinkedIn"] },
  "peeking-iterator":          { time:"O(1)",  space:"O(1)",   elo:null, freq:2.3, companies:["Amazon","Meta","Google","Microsoft","Bloomberg","Apple"] },
  "flatten-nested-list-iterator": { time:"O(1)", space:"O(n)", elo:null, freq:12.4, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","LinkedIn","Twitter"] },
  "zigzag-iterator":           { time:"O(1)",  space:"O(k)",   elo:null, freq:3.9, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "binary-search-tree-iterator": { time:"O(1)", space:"O(h)",  elo:null, freq:6.2, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber","LinkedIn"] },
  "design-snake-game":         { time:"O(1)",  space:"O(w·h)", elo:null, freq:7.8, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber"] },
  "logger-rate-limiter":       { time:"O(1)",  space:"O(n)",   elo:null, freq:16.3, companies:["Amazon","Meta","Google","Microsoft","Bloomberg","Apple"] },
  "moving-average-from-data-stream": { time:"O(1)", space:"O(k)", elo:null, freq:9.3, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "shortest-word-distance":    { time:"O(n)",  space:"O(1)",   elo:null, freq:6.2, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","LinkedIn"] },
  "shortest-word-distance-ii": { time:"O(n)",  space:"O(n)",   elo:null, freq:3.1, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","LinkedIn"] },

  // -- Misc. Popular Problems ---------------------------------------------
  "first-missing-positive":    { time:"O(n)",  space:"O(1)",   elo:null, freq:24.8, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber","Salesforce"] },
  "find-the-duplicate-number": { time:"O(n)",  space:"O(1)",   elo:null, freq:17.1, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber"] },
  "majority-element":          { time:"O(n)",  space:"O(1)",   elo:null, freq:17.1, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Adobe"] },
  "majority-element-ii":       { time:"O(n)",  space:"O(1)",   elo:null, freq:7.8, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "next-permutation":          { time:"O(n)",  space:"O(1)",   elo:null, freq:24.8, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber","Goldman Sachs"] },
  "next-greater-element-i":    { time:"O(n+m)", space:"O(n)",  elo:null, freq:12.4, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },
  "next-greater-element-ii":   { time:"O(n)",  space:"O(n)",   elo:null, freq:12.4, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "candy":                     { time:"O(n)",  space:"O(n)",   elo:null, freq:17.8, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },
  "car-pooling":               { time:"O(n log n)", space:"O(n)", elo:null, freq:10.1, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },
  "minimum-number-of-taps-to-open-to-water-a-garden": { time:"O(n)", space:"O(n)", elo:null, freq:10.1, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "maximum-points-you-can-obtain-from-cards": { time:"O(n)", space:"O(1)", elo:null, freq:9.3, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "boats-to-save-people":      { time:"O(n log n)", space:"O(1)", elo:null, freq:8.5, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "range-sum-query-immutable": { time:"O(1)",  space:"O(n)",   elo:null, freq:6.2, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "range-sum-query-2d-immutable": { time:"O(1)", space:"O(m·n)", elo:null, freq:7, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },
  "contiguous-array":          { time:"O(n)",  space:"O(n)",   elo:null, freq:10.9, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "subarray-sums-divisible-by-k": { time:"O(n)", space:"O(k)", elo:null, freq:8.5, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "continuous-subarray-sum":   { time:"O(n)",  space:"O(k)",   elo:null, freq:7.8, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "random-pick-with-weight":   { time:"O(log n)", space:"O(n)", elo:null, freq:20.2, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber","LinkedIn"] },
  "kth-smallest-element-in-a-sorted-matrix": { time:"O(n log r)", space:"O(1)", elo:null, freq:7.8, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },
  "4sum":                      { time:"O(n³)", space:"O(1)",   elo:null, freq:14.7, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },
  "4sum-ii":                   { time:"O(n²)", space:"O(n²)",  elo:null, freq:2.3, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "concatenation-of-consecutive-binary-numbers": { time:"O(n)", space:"O(1)", elo:null, freq:2.3, companies:["Amazon","Meta","Google","Microsoft"] },
  "smallest-range-covering-elements-from-k-lists": { time:"O(n log k)", space:"O(k)", elo:null, freq:7.8, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "employee-importance":       { time:"O(n)",  space:"O(n)",   elo:null, freq:3.9, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "map-sum-pairs":             { time:"O(k)",  space:"O(n·k)", elo:null, freq:1.6, companies:["Amazon","Meta","Google","Microsoft"] },
  "maximum-width-of-binary-tree": { time:"O(n)", space:"O(n)", elo:null, freq:6.2, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },
  "parallel-courses":          { time:"O(n+p)", space:"O(n+p)", elo:null, freq:5.4, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Uber"] },
  "maximize-distance-to-closest-person": { time:"O(n)", space:"O(1)", elo:null, freq:6.2, companies:["Amazon","Meta","Google","Microsoft"] },
  "exam-room":                 { time:"O(n)",  space:"O(n)",   elo:null, freq:4.7, companies:["Amazon","Meta","Google","Microsoft"] },
  "range-addition":            { time:"O(n+q)", space:"O(1)",  elo:null, freq:2.3, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "max-sum-of-rectangle-no-larger-than-k": { time:"O(m²·n log n)", space:"O(n)", elo:null, freq:2.3, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "my-calendar-i":             { time:"O(n)",  space:"O(n)",   elo:null, freq:8.5, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "my-calendar-ii":            { time:"O(n)",  space:"O(n)",   elo:null, freq:2.3, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "my-calendar-iii":           { time:"O(n²)", space:"O(n)",   elo:null, freq:0.8, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "k-empty-slots":             { time:"O(n)",  space:"O(n)",   elo:null, freq:0.8, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "minimum-domino-rotations-for-equal-row": { time:"O(n)", space:"O(1)", elo:null, freq:3.1, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "invalid-transactions":      { time:"O(n²)", space:"O(n)",   elo:null, freq:5.4, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "divide-array-in-sets-of-k-consecutive-numbers": { time:"O(n log n)", space:"O(n)", elo:null, freq:1.6, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "reorder-data-in-log-files": { time:"O(n log n)", space:"O(n)", elo:null, freq:3.1, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "expression-add-operators":  { time:"O(n·4^n)", space:"O(n)", elo:null, freq:5.4, companies:["Amazon","Meta","Google","Microsoft","Bloomberg","Uber"] },
  "wildcard-matching":         { time:"O(m·n)", space:"O(n)",  elo:null, freq:13.2, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber"] },
  "string-to-integer-atoi":    { time:"O(n)",  space:"O(1)",   elo:null, freq:15.5, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber","LinkedIn","Goldman Sachs"] },
  "zigzag-conversion":         { time:"O(n)",  space:"O(n)",   elo:null, freq:14.7, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Adobe"] },
  "integer-to-roman":          { time:"O(1)",  space:"O(1)",   elo:null, freq:24, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","LinkedIn"] },
  "roman-to-integer":          { time:"O(n)",  space:"O(1)",   elo:null, freq:29.5, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Adobe","Uber"] },
  "text-justification":        { time:"O(n)",  space:"O(n)",   elo:null, freq:34.1, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber","LinkedIn"] },
  "integer-to-english-words":  { time:"O(log n)", space:"O(1)", elo:null, freq:17.8, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber","LinkedIn"] },
  "basic-calculator":          { time:"O(n)",  space:"O(n)",   elo:null, freq:17.8, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber","LinkedIn"] },
  "basic-calculator-iii":      { time:"O(n)",  space:"O(n)",   elo:null, freq:12.4, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Uber"] },
  "flatten-2d-vector":         { time:"O(1)",  space:"O(n)",   elo:null, freq:3.1, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },

  // -- More recent popular problems ---------------------------------------
  "sliding-window-median":      { time:"O(n log k)", space:"O(k)", elo:null, freq:8.5, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "ipo":                        { time:"O(n log n)", space:"O(n)", elo:null, freq:8.5, companies:["Amazon","Meta","Google","Microsoft"] },
  "find-k-th-smallest-pair-distance": { time:"O(n log n + n log m)", space:"O(1)", elo:null, freq:3.9, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "find-k-closest-elements":   { time:"O(log n + k)", space:"O(1)", elo:null, freq:14.7, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber"] },
  "guess-number-higher-or-lower": { time:"O(log n)", space:"O(1)", elo:null, freq:5.4, companies:["Amazon","Meta","Google","Microsoft"] },
  "guess-number-higher-or-lower-ii": { time:"O(n²)", space:"O(n²)", elo:null, freq:2.3, companies:["Amazon","Meta","Google","Microsoft"] },
  "valid-triangle-number":     { time:"O(n²)", space:"O(1)",   elo:null, freq:7, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "find-the-celebrity":        { time:"O(n)",  space:"O(1)",   elo:null, freq:9.3, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","LinkedIn"] },
  "first-bad-version":         { time:"O(log n)", space:"O(1)", elo:null, freq:5.4, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },
  "populating-next-right-pointers-in-each-node": { time:"O(n)", space:"O(1)", elo:null, freq:6.2, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },
  "populating-next-right-pointers-in-each-node-ii": { time:"O(n)", space:"O(1)", elo:null, freq:5.4, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "convert-sorted-array-to-binary-search-tree": { time:"O(n)", space:"O(log n)", elo:null, freq:7, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },
  "convert-sorted-list-to-binary-search-tree": { time:"O(n)", space:"O(log n)", elo:null, freq:7, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "path-sum":                   { time:"O(n)",  space:"O(h)",   elo:null, freq:7.8, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "path-sum-ii":                { time:"O(n²)", space:"O(n)",   elo:null, freq:7.8, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "path-sum-iii":               { time:"O(n)",  space:"O(n)",   elo:null, freq:7.8, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "sum-root-to-leaf-numbers":  { time:"O(n)",  space:"O(h)",   elo:null, freq:5.4, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "binary-tree-paths":         { time:"O(n)",  space:"O(n)",   elo:null, freq:5.4, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "find-leaves-of-binary-tree": { time:"O(n)",  space:"O(n)",  elo:null, freq:4.7, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "all-nodes-distance-k-in-binary-tree": { time:"O(n)", space:"O(n)", elo:null, freq:10.1, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple","Uber"] },
  "time-needed-to-inform-all-employees": { time:"O(n)", space:"O(n)", elo:null, freq:3.9, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "number-of-operations-to-make-network-connected": { time:"O(n+e)", space:"O(n)", elo:null, freq:7.8, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "as-far-from-land-as-possible": { time:"O(n²)", space:"O(n²)", elo:null, freq:4.7, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "shortest-bridge":            { time:"O(n²)", space:"O(n²)",  elo:null, freq:11.6, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "shortest-path-in-a-grid-with-obstacles-elimination": { time:"O(m·n·k)", space:"O(m·n·k)", elo:null, freq:10.9, companies:["Amazon","Meta","Google","Microsoft","Bloomberg","Apple","Uber"] },
  "snakes-and-ladders":        { time:"O(n²)", space:"O(n²)",  elo:null, freq:9.3, companies:["Amazon","Meta","Microsoft","Google","Bloomberg","Apple"] },
  "minimum-genetic-mutation":  { time:"O(n·L)", space:"O(n)",  elo:null, freq:4.7, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "minimum-jumps-to-reach-home": { time:"O(n)", space:"O(n)",  elo:null, freq:2.3, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "jump-game-iii":             { time:"O(n)",  space:"O(n)",   elo:null, freq:2.3, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "jump-game-iv":              { time:"O(n)",  space:"O(n)",   elo:null, freq:2.3, companies:["Amazon","Meta","Google","Microsoft","Bloomberg","Apple"] },
  "jump-game-v":               { time:"O(n·d)", space:"O(n)",  elo:null, freq:0.8, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "jump-game-vii":             { time:"O(n)",  space:"O(n)",   elo:null, freq:1.6, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "stone-game-ii":             { time:"O(n²)", space:"O(n²)",  elo:null, freq:3.9, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "stone-game-iii":            { time:"O(n)",  space:"O(n)",   elo:null, freq:1.6, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "stone-game-iv":             { time:"O(n·vn)", space:"O(n)", elo:null, freq:0.8, companies:["Amazon","Meta","Google","Microsoft"] },
  "stone-game-v":              { time:"O(n²)", space:"O(n²)",  elo:null, freq:0.8, companies:["Amazon","Meta","Google","Microsoft"] },
  "stone-game-vi":             { time:"O(n log n)", space:"O(n)", elo:null, freq:3.1, companies:["Amazon","Meta","Google","Microsoft"] },
  "stone-game-vii":            { time:"O(n²)", space:"O(n²)",  elo:null, freq:1.6, companies:["Amazon","Meta","Google","Microsoft"] },
  "max-value-of-equation":     { time:"O(n)",  space:"O(n)",   elo:null, freq:0.8, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "constrained-subsequence-sum": { time:"O(n)", space:"O(n)",  elo:null, freq:1.6, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "closest-room":              { time:"O(n log n + q log n)", space:"O(n)", elo:null, freq:0.8, companies:["Amazon","Meta","Google","Microsoft"] },
  "count-vowels-permutation":  { time:"O(n)",  space:"O(1)",   elo:null, freq:0.8, companies:["Amazon","Meta","Google","Microsoft"] },
  "minimum-swaps-to-make-strings-equal": { time:"O(n)", space:"O(1)", elo:null, freq:3.1, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "minimum-number-of-flips-to-make-the-binary-string-alternating": { time:"O(n)", space:"O(1)", elo:null, freq:3.9, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "minimum-number-of-flips-to-make-binary-grid-palindromic-i": { time:"O(m·n)", space:"O(1)", elo:null, freq:3.1, companies:["Amazon","Meta","Google","Microsoft"] },
  "reducing-dishes":           { time:"O(n log n)", space:"O(1)", elo:null, freq:1.6, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "minimum-difficulty-of-a-job-schedule": { time:"O(n²·d)", space:"O(n·d)", elo:null, freq:5.4, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "paint-house-iii":           { time:"O(m·t·n²)", space:"O(t·n)", elo:null, freq:2.3, companies:["Amazon","Meta","Google","Microsoft"] },
  "maximum-side-length-of-a-square-with-sum-less-than-or-equal-to-threshold": { time:"O(m·n)", space:"O(m·n)", elo:null, freq:3.9, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "number-of-submatrices-that-sum-to-target": { time:"O(m²·n)", space:"O(n)", elo:null, freq:3.1, companies:["Amazon","Meta","Google","Microsoft","Bloomberg","Apple"] },
  "delete-operation-for-two-strings": { time:"O(m·n)", space:"O(n)", elo:null, freq:3.1, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "minimum-ascii-delete-sum-for-two-strings": { time:"O(m·n)", space:"O(n)", elo:null, freq:3.1, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "uncrossed-lines":           { time:"O(m·n)", space:"O(n)",  elo:null, freq:3.1, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "maximum-length-of-repeated-subarray": { time:"O(m·n)", space:"O(n)", elo:null, freq:5.4, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "find-the-index-of-the-first-occurrence-in-a-string": { time:"O(m+n)", space:"O(1)", elo:null, freq:11.6, companies:["Amazon","Meta","Google","Microsoft"] },
  "shortest-palindrome":       { time:"O(n)",  space:"O(n)",   elo:null, freq:7, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "repeated-dna-sequences":    { time:"O(n)",  space:"O(n)",   elo:null, freq:5.4, companies:["Amazon","Meta","Google","Microsoft","Bloomberg","LinkedIn"] },
  "distinct-echo-substrings":  { time:"O(n²)", space:"O(n)",   elo:null, freq:0.8, companies:["Amazon","Meta","Google","Microsoft"] },
  "camelcase-matching":        { time:"O(n·L)", space:"O(1)",  elo:null, freq:1.6, companies:["Amazon","Meta","Google","Microsoft"] },
  "online-stock-span":         { time:"O(n)",  space:"O(n)",   elo:null, freq:4.7, companies:["Amazon","Meta","Microsoft","Google","Bloomberg"] },
  "sum-of-subarray-minimums":  { time:"O(n)",  space:"O(n)",   elo:null, freq:10.1, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "sum-of-subarray-ranges":    { time:"O(n)",  space:"O(n)",   elo:null, freq:7.8, companies:["Amazon","Meta","Google","Microsoft"] },
  "max-chunks-to-make-sorted": { time:"O(n)",  space:"O(1)",   elo:null, freq:5.4, companies:["Amazon","Meta","Google","Microsoft"] },
  "max-chunks-to-make-sorted-ii": { time:"O(n)", space:"O(n)", elo:null, freq:3.1, companies:["Amazon","Meta","Google","Microsoft"] },
  "number-of-atoms":           { time:"O(n²)", space:"O(n)",   elo:null, freq:6.2, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] },
  "robot-return-to-origin":    { time:"O(n)",  space:"O(1)",   elo:null, freq:3.9, companies:["Amazon","Meta","Google","Microsoft","Goldman Sachs"] },
  "robot-bounded-in-circle":   { time:"O(n)",  space:"O(1)",   elo:null, freq:8.5, companies:["Amazon","Meta","Google","Microsoft","Goldman Sachs"] },
  "minimum-area-rectangle":    { time:"O(n²)", space:"O(n)",   elo:null, freq:6.2, companies:["Amazon","Meta","Google","Microsoft"] },
  "minimum-area-rectangle-ii": { time:"O(n³)", space:"O(n)",   elo:null, freq:1.6, companies:["Amazon","Meta","Google","Microsoft"] },
  "erect-the-fence":           { time:"O(n log n)", space:"O(n)", elo:null, freq:2.3, companies:["Amazon","Meta","Google","Microsoft"] },
  "convex-hull":               { time:"O(n log n)", space:"O(n)", elo:null, freq:3.1, companies:["Amazon","Meta","Google","Microsoft"] },
  "escape-a-large-maze":       { time:"O(m²)", space:"O(m²)",  elo:null, freq:2.3, companies:["Amazon","Meta","Google","Microsoft"] },
  "tiling-a-rectangle-with-the-fewest-squares": { time:"O(n·m)", space:"O(n·m)", elo:null, freq:2.3, companies:["Amazon","Meta","Google","Microsoft"] },
  "strong-password-checker":   { time:"O(n)",  space:"O(1)",   elo:null, freq:4.7, companies:["Amazon","Meta","Google","Microsoft"] },
  "cracking-the-safe":        { time:"O(n·k^n)", space:"O(n·k^n)", elo:null, freq:0.8, companies:["Amazon","Meta","Google","Microsoft"] },
  "cat-and-mouse":            { time:"O(n³)", space:"O(n²)",   elo:null, freq:3.9, companies:["Amazon","Meta","Google","Microsoft"] },
  "all-paths-from-source-to-target": { time:"O(n·2^n)", space:"O(n)", elo:null, freq:4.7, companies:["Amazon","Meta","Google","Microsoft","Bloomberg"] }
};
